sudo: false
language: ruby
rvm:
- 2.4.1
- 2.3.3
- 2.2.6
- 2.1.10
before_install: gem install bundler -v 1.13.7
service_name: travis-ci
notifications:
  slack:
    secure: SwkR+0rZUYXK/nvYa6PBYj310weZNQyHrMFp+lqW+9vmrvefJ25LJ7qhOM7HV4lpFWC1dkSNcrnATFia77ufS4b77VaGewl2r+Olx4UuXJiPKeyigATnc3djZ9VDSXXqMojf0D0NxC+xyq0k4v5CKZvv3CUoU6fnJZd0hwHGRMFPuZbL7uQu0PD0lryhg/QhzXgGWPA80h0IioehyAAJ1mmDF0y9yUckzMDfeyIhVmJD22IwNeezpqpZknkAo35Ev43pRTZlo3A2+WzuZoNY9lPRwoC+kMEzhQqBRNj4OanCPo7iCId152qLjnJdoukSAso3AEa7SoQr3SRduYuAvj8X7ItWnzGKNCSyatBnAU6fXcbRaRHNaqTCAUYBx6dWV5xqRa20EYKX97xLGRA4hIxLHeS3pZckcBoi1O81cLsXbBtT1hxffy48gpxANf0a2+pjkMz61BbnPhfNEvH/SmZUsyLBQTZp9LIKX54qT5Gwr8aGVl638UK70r9PqBL5yGIOCIWUtUGAipSAHkDFfe2l6w3sIqXNP9P4RuVSQhon1LzS/rMXU9PUqka5Dzvnn4+ndiqNm+QfwUKJznYeROhY+tO/VIbZ/T3LGReyf103rvpiIuNzkU5ZL6PQubgoVhN4cjK29zEcMygtZPmqmIqf2PPTURCD+XZ5BiQP/+4=
